### ISSUE TITLE
ValueError: Columns must be same length as key

### ISSUE THREAD

**Issue by pjatx** [TeneoPython01/calendar_table#1]
Thanks for creating this! Running into an issue when trying to run this. 

The script is throwing the following error when trying to run the script from this line: https://github.com/TeneoPython01/calendar_table/blob/master/calendar_table.py#L256

```
ValueError: Columns must be same length as key
```

Any insight?

**Comment by TeneoPython01** [comment]
I ran the code tonight using my old dev box and it ran without issues.  My guess is some of the libraries used when this was written have become out of date.

For reference, the code ran tonight (June 7, 2023) using Python 3.7.3 ; pandas 0.25.1 ; numpy 1.16.2

You could try to run the code using the versions noted above, or you could adjust the code based on the traceback.  The errors are likely due to functions deprecated over time.

Let me know if you determine the fix.  Thanks
